[package]
name = "py-rattler"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[lib]
name = "rattler"
crate-type = ["cdylib"]

[dependencies]
futures = "*"
rattler_conda_types = { path = "../crates/rattler_conda_types", default-features = false }
rattler_repodata_gateway = { path = "../crates/rattler_repodata_gateway", default-features = false }
rattler_networking = { path = "../crates/rattler_networking", default-features = false }
reqwest = "*"
pyo3 = { version = "0.19", features = [
    "abi3-py38",
    "extension-module",
    "multiple-pymethods",
] }
pyo3-asyncio = { version = "0.19", features = ["tokio-runtime"] }
tokio = { version = "1.32" }
thiserror = "1.0.44"
url = "*"

# Prevent package from thinking it's in the workspace
[workspace]
