[package]
name = "py-rattler"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[lib]
name = "rattler"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
futures = "0.3.28"

rattler = { path = "../crates/rattler" }
rattler_repodata_gateway = { path = "../crates/rattler_repodata_gateway", features = [
    "sparse",
] }
rattler_conda_types = { path = "../crates/rattler_conda_types", default-features = false }
rattler_networking = { path = "../crates/rattler_networking", default-features = false }
rattler_shell = { path = "../crates/rattler_shell", default-features = false }
rattler_virtual_packages = { path = "../crates/rattler_virtual_packages" }
rattler_solve = { path = "../crates/rattler_solve", features = ["resolvo"] }

pyo3 = { version = "0.19", features = [
    "abi3-py38",
    "extension-module",
    "multiple-pymethods",
] }
pyo3-asyncio = { version = "0.19", features = ["tokio-runtime"] }
tokio = { version = "1.32" }

thiserror = "1.0.44"
url = "2.4.1"

# Prevent package from thinking it's in the workspace
[workspace]
